### ISSUE TITLE
suffix ".html"

### ISSUE THREAD

**Issue by qiwuteng** [Cyrusky/hexo-backlink#13]
the new link has suffix ".html", but I don't need it. How to remove the suffix ".html"?
<img width="172" alt="image" src="https://user-images.githubusercontent.com/99115095/233792289-d3a91c33-f641-4f75-b2f9-5ca8fb5d50a5.png">

**Comment by Cyrusky** [comment]
It's a deprecat library. so I have to read my code and figure out what's wrong with it....sorry it might take some time.

**Comment by qiwuteng** [comment]
> 

Thanks, I found that the problem came from the blog theme, I changed the theme and it worked 😄

**Comment by qiwuteng** [comment]
> It's a deprecat library. so I have to read my code and figure out what's wrong with it....sorry it might take some time.

Thanks, I found that the problem came from the blog theme, I changed the theme and it worked 😄
