### ISSUE TITLE
Does not work in windows10.

### ISSUE THREAD

**Issue by harryisfish** [Cyrusky/hexo-backlink#7]
When I run the install command `npm install hexo-backlink`  
It return:  
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):  
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})  

+ hexo-backlink@0.1.2  
```
Will it support Windows platform in the futrue?

**Comment by Cyrusky** [comment]
Hi, I think I have already fixed the issue by updating the npm package to version 0.1.3, you should have a try, if it's still not working, please delete the `.lock` file in the root directory of the project. and reinstall the package.

**Comment by harryisfish** [comment]
Don't work when I reinstall it or install in a brand new PC environment. It keep warning me as I mentioned.  
I guessed it would work fine even with warning, but the  `[[title]]` in the `source` file or the `public` file never get change after `hexo g` `hexo s` `hexo d`.  
Sorry to report that.

**Comment by Cyrusky** [comment]
Sorry about that. If you have solutions then you can create a PR for this issue. I really want to do that but have no time recent weeks. Or if you can’t I will check it later. And I will keep this issue as OPEN state until I check it.

**Comment by harryisfish** [comment]
A huge thanks is due to you.  
I will read the code in the near future.

**Comment by harryisfish** [comment]
Maybe it's an Obsidian setting problem.  The link format is the point.   
I reset the options as follow:  
> "Settings" -> "Files & Links" -> "New link format" , setting as "Relative path to file"  
> "Settings" -> "Files & Links" -> "Use [[Wikilinks]]" , keeping it ON 

Everything seems to be working well.  
I guess it depends on the working principle of hexo-backlink.  If the settings in your Obsidian are similar to mine, please mention them in README.md for prevention at first installation.  (PR #9 )
Anyway, I run it well now. I will read the code to seek ways to the platform warning problem in the near future.
